i = input('Digite algo:')
print(type(i))
print('É espaço!', i.isspace())
print('É um número ou caractere alfabético!', i.isalnum())
print('É um caractere alfabético!', i.isalpha())
print('Está presente na tabela ASCII!', i.isascii())
print('É decimal!', i.isdecimal())
print('É um digito!', i.isdigit())
print('É um identificador!', i.isidentifier())
print('Está escrito em letras minúsculas!', i.islower())
print('Está escrito em letras maiúsculas!', i.isupper())
print('Está capitalizada!', i.istitle())